resources:
  repositories:
    - repository: devOps_templates
      type: git
      name: DevOps

jobs:
- template: pipelines/trg.extensions.yml@devOps_templates
  parameters:
    name: 'Publish PreRelease Packages'
    vmImage: 'ubuntu-latest'
      